name: Lint and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.16.x

      - name: Verify formatting
        run: deno fmt --config=deno.json --check

      - name: Run linter
        run: deno lint --config=deno.json

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.16.x

      - name: Cache dependencies
        run: deno cache lib/**/*deps.ts

      - name: Run tests
        run: deno test --allow-all lib
